import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '../shared/Sidebar';
import Header from '../shared/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Fruits-Collection',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='lg:mx-auto max-w-[1920px]'>
        <div className='relative '>
          <div className='fixed -top-auto '>
            <Header />
          </div>
          <div className=' '>
            <div className='flex flex-col md:flex-row'>
              <div className='fixed flex items-center justify-center bottom-0 md:bottom-auto w-full md:w-[70px] md:mt-[60px] order-2 md:order-1'>
                <Sidebar />
              </div>
              <div className='bg-yellow-300 w-full md:ml-[70px] mt-[60px] md:order-2 h-[1800px]'>
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
