import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './shared/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fruits-Collection',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='relative h-screen'>
        <div className='mx-1 md:mx-2 lg:mx-4 ' >
          <div className='flex flex-col md:flex-row'>
            <div className='fixed bottom-0 w-full md:w-[70px] order-2 md:order-1'>
              <Sidebar />
            </div>
            <div className='bg-yellow-300 w-full md:ml-[70px] md:order-2 h-[1800px]'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
